on: [push]
name: build
jobs:
  runhaskell:
    name: Build and Test Tasty-Spectrum
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.10'
          cabal-version: 'latest'
      - run: | 
        cabal build
        cabal test tasty-spectrum-tests